### ISSUE TITLE
Plan to get repo back on its feet

### ISSUE THREAD

**Issue by lukeapage** [docstrap/docstrap#128]
- [x] Get the repo into a good state - see PR #125 - please feel free to help/coordinate with me to get back to a good state to continue from. Lets do this first?
 - [x] do a release
 - [x] Merge bugfix PR's
 - [x] sort out links #126 
 - [x] Sort out whitespace issues (line endings #127)
 - [x] update from bootswatch
 - [ ] do a release

@thealjey @fisch0920 does that sound like a plan? If you have a better plan please feel free to suggest

**Comment by lukeapage** [comment]
Regarding the PR #125 it seems like such alot of work to track down the changes in between those 2 versions I almost wonder whether it wouldn't be better just fixing the 2/3 issues they undid - however some of the changes seem a bit weird

**Comment by lukeapage** [comment]
In the end I undid everything that looked suspicious and made PR's for any changes I removed.
